[package]
name = "suprps"
version = "0.1.0"
edition = "2024"

[dependencies]
udev = "0.9.3"
nix = { version = "0.30.1", features = ["poll"] }
serde = { version = "1.0.219", features = ["derive"] }
dirs = "6.0.0"
toml = "0.8.22"
log = "0.4.27"
systemd-journal-logger = "2.2.2"
